spring:
  datasource:
    username: postgres
    password: password
    url: 'jdbc:postgresql://localhost:5433/products'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

springdoc:
  swagger-ui:
    use-root-path: true
  cache:
    disabled: true
