server:
  port: 8084

endpoints:
  customerOrdersGateway: "http://localhost:8084/api/v1/orders/"
  orderService: "http://localhost:8080/api/v1/orders/"
  customerService: "http://localhost:8082/api/v1/customers/"
  productService: "http://localhost:8081/api/v1/products/"

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

springdoc:
  swagger-ui:
    use-root-path: true
  cache:
    disabled: true
